### ISSUE TITLE
Add more news websites to scrape news headlines

### ISSUE THREAD

**Issue by amitsagtani97** [amitsagtani97/Python-Scripts#2]
At present news from TimesOfIndia website is scrapped.
Scrape more websites for the news.

**Comment by Divya063** [comment]
@amitsagtani97 I would like to work on this

**Comment by amitsagtani97** [comment]
@Divya063  Sure, the main aim is to scrap news from different websites and display them as notifications at regular interval of time.

**Comment by Divya063** [comment]
Thanks for the info, I'm on it!

**Comment by ItachiUchiha1998** [comment]
i would like to work on this

**Comment by amitsagtani97** [comment]
@ItachiUchiha1998 Sure, in case of any doubt you can ask :)

**Comment by ItachiUchiha1998** [comment]
I have made a scraper which would scrape the data from the site : "https://khabar.ndtv.com/topic/news/news"
right now it fetches : title,image and description and stores in mongoDB
is it suitable for you?

**Comment by amitsagtani97** [comment]
@ItachiUchiha1998 hi, this projects aims at scrapping news from different websites and display them as NOTIFICATIONS at desktop, so can you please edit your code and include the news from your scrapper into present code and display them as notifications instead of storing them in mongoDB.
This helps users to keep them aware of current news headlines and stories without visiting different websites :)
May also help in improving general knowledge.

**Comment by ItachiUchiha1998** [comment]
I have made the proposed changes and submitted a PR please review it..
