### ISSUE TITLE
Add more cool python scripts.

### ISSUE THREAD

**Issue by amitsagtani97** [amitsagtani97/Python-Scripts#5]
Share your cool python projects and scripts which are helpful in daily life.
Please add a README file too. :)

**Comment by Naman9639** [comment]
@amitsagtani97 I would like to work on this issue.

**Comment by rahulbandari2499** [comment]
@amitsagtani97 I would like to work on this

**Comment by Naman9639** [comment]
Please review my PR https://github.com/amitsagtani97/Python-Scripts/pull/8
